### ISSUE TITLE
Gettin Installation Error

### ISSUE THREAD

**Issue by attacker34** [lc/hacks#2]
Hi @lc 

I am getting this Error while running installation command==> go build -o ~/go/bin/gau getallurls.go 

```
can't load package: package main: 
getallurls.go:7:1: expected 'package', found '<'

```

**Comment by lc** [comment]
Hi @attacker34,

This should work: 

```
▻ git clone https://github.com/lc/hacks && cd hacks/getallurls
▻ go build -o $GOPATH/bin/gau getallurls.go
```

If not, you can do this: `go get -u github.com/lc/hacks/getallurls/` and then `mv $GOPATH/bin/getallurls $GOPATH/bin/gau`
