### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vishnugadupudi** [lc/hacks#3]
vishnui@cloudshell:~/Hackerone/Paid/ATT/att.com (spry-utility-263500)$ cat hosts | getallurls
http://1-800-conference.com:80/
http://1-800-conference.com:80/Common/images/bars/long_blue_line.gif
http://1-800-conference.com:80/Common/images/bars/shim.gif
http://1-800-conference.com:80/Common/images/bottom_menu.gif
http://1-800-conference.com:80/Common/images/divider4.gif
http://1-800-conference.com:80/Common/images/sbclogo.gif
http://1-800-conference.com:80/Common/images/shim.gif
http://1-800-conference.com/favicon.ico
http://www.1-800-conference.com:80/products/1800conference/0,5736,4,00.html
http://www.1-800-conference.com:80/products/1800conference/0,5736,5,00.html
http://www.1-800-conference.com:80/products/1800conference/0,5736,6,00.html
http://1-800-conference.com:80/products/1800conference/1-800_head.jpg
http://1-800-conference.com:80/robots.txt

2020/02/09 00:03:27 Could not decode json: invalid character '<' looking for beginning of value

**Comment by lc** [comment]
Hey @vishu10x00,

I believe this is because you've either been rate-limited by AlienVault or the host you were trying to get URL's for had too many results that the OTX API didn't like:

```golang
 69 func getOtxUrls(hostname string) ([]string, error) {
-- snip --
 73                 r, err := client.Get(fmt.Sprintf("https://otx.alienvault.com/api/v1/indicators/hostname/%s/url_list?limit=50&page=%d", hostname, page))
-- snip --
 82                 o := &OTXResult{}
 83                 err = json.Unmarshal(bytes, o)
 84                 if err != nil {
 85                         log.Fatalf("Could not decode json: %s\n", err)
 86                 }
```

This is expected behavior and not a bug on the tool's side.

Thanks.
